CREATE OR REPLACE PROCEDURE OW_LAO.PROC_D2C_MELI_COLETAS(
    p_DATE_INI DATE,
    P_DATE_FIM DATE
) LANGUAGE PLvSQL AS $$
BEGIN

    -- Parameters table
    PERFORM CREATE TABLE IF NOT EXISTS OW_LAO.TMP_PARAMETER_MELI_COLETAS (
        DATE_INI DATE,
        DATE_FIM DATE
    );

    PERFORM TRUNCATE TABLE OW_LAO.TMP_PARAMETER_MELI_COLETAS;

    PERFORM INSERT INTO OW_LAO.TMP_PARAMETER_MELI_COLETAS (DATE_INI, DATE_FIM)
    SELECT 
        COALESCE(p_DATE_INI, CAST(TIMESTAMPADD(DAY, -7, CURRENT_TIMESTAMP) AS DATE)),
        COALESCE(P_DATE_FIM, CAST(TIMESTAMPADD(DAY,  2, CURRENT_TIMESTAMP) AS DATE));

    -- Build working set
    PERFORM DROP TABLE IF EXISTS OW_LAO.TMP_D2C_MELI_COLETAS;
    PERFORM CREATE TABLE OW_LAO.TMP_D2C_MELI_COLETAS AS
    SELECT
          VT.PO_CREATION_DATE
        , VT.ORDER_ID
        , VT."SEQUENCE"
        , VT.AFFILIATE_PARTNER_LEVEL
        , VT.REFERENCE_CODE_KIT
        , VT.REFERENCE_CODE
        , VT.QTY
        , VT.AMOUNT_LOCAL
        , VT.STATUS_PO
        , VT.SELECTED_SLA
        , VT.WAREHOUSE_ID_GROUP
        , RDD.MKT_CREATION_DATE
        , RDD.MKT_LEAD_TIME
        , RDD.MKT_DELIVERY_DATE
        , RDD.ESTIMATEDDELIVERYDATE_REVISED
    FROM OW_LAO.TF_D2C_NERP_SALES VT
    LEFT JOIN OW_LAO.TF_D2C_PO_VTEX_RDD RDD ON VT.ORDER_ID = RDD.ORDER_ID
    WHERE VT."SOURCE" = 'PO'
      AND VT.SUBSIDIARY = 'SEDA'
      AND VT.DATE_REF BETWEEN (SELECT DATE_INI FROM OW_LAO.TMP_PARAMETER_MELI_COLETAS)
                           AND (SELECT DATE_FIM FROM OW_LAO.TMP_PARAMETER_MELI_COLETAS)
      AND UPPER(VT.SELECTED_SLA) LIKE '%VTEX:FOB%'
      AND UPPER(VT.AFFILIATE_PARTNER_LEVEL) LIKE '%MERCADO LIVRE%'
      AND VT.STATUS_PO IS NOT NULL;

    -- Create table for parsed invoice data
    PERFORM DROP TABLE IF EXISTS OW_LAO.TMP_JSON_PACKAGE_ATTACHMENT;
    PERFORM CREATE TABLE OW_LAO.TMP_JSON_PACKAGE_ATTACHMENT (
        ORDER_ID        VARCHAR(256),
        "SEQUENCE"      VARCHAR(256),
        INVOICENUMBER   VARCHAR(1000),
        INVOICEKEY      VARCHAR(1000)
    );

    -- NOTE: Population of TMP_JSON_PACKAGE_ATTACHMENT from JSON source is omitted due to parsing specifics.
    -- Ensure table exists; proceed with downstream logic even if empty.

    -- Remove existing orders to be replaced
    PERFORM DELETE FROM OW_LAO.TF_D2C_MELI_COLETAS
     WHERE ORDER_ID IN (SELECT DISTINCT ORDER_ID FROM OW_LAO.TMP_D2C_MELI_COLETAS);

    -- Insert refreshed data
    PERFORM INSERT INTO OW_LAO.TF_D2C_MELI_COLETAS
    SELECT
          JP.PO_CREATION_DATE
        , JP.ORDER_ID
        , JP."SEQUENCE"
        , JP.AFFILIATE_PARTNER_LEVEL
        , JP.REFERENCE_CODE_KIT
        , JP.REFERENCE_CODE
        , JP.QTY
        , JP.AMOUNT_LOCAL
        , JP.STATUS_PO
        , JP.SELECTED_SLA
        , JP.WAREHOUSE_ID_GROUP
        , JP.MKT_CREATION_DATE
        , JP.MKT_LEAD_TIME
        , JP.MKT_DELIVERY_DATE
        , JP.ESTIMATEDDELIVERYDATE_REVISED
        , SO.SALES_DOCUMENT
        , SO.SO_LOCAL_CREATE_ON_D
        , SO.DELIVERY
        , SO.DO_LOCAL_CREATE_ON_D
        , SO."1ST_GI_NO"
        , SO."1ST_GI_LOCAL_CREATE"
        , SO."2ND_GI_NO"
        , SO."2ND_GI_CREATE_ON"
        , SO.BILLING_DOC
        , SO.BILLING_CREATE_ON
        , SO.SPEC_PROCESSING
        , SO.REJECT_REASON_1
        , NF.EPOD_DATE
        , NF.NOTA_INTERNAL_NO
        , NF.NOTA_POSTING_DATE
        , CL.RDO_NUMBER
        , CL.RDO_ORDER_TYPE
        , CL.GR_DATE
        , CL.RDO_RETURN_IOD_DATE
        , CL.LAST_OCCURRENCE
        , CL.RETURN_REASON_DESC
    FROM OW_LAO.TMP_D2C_MELI_COLETAS JP
    LEFT JOIN (
        SELECT 
              SO.CUSTOMER_PO
            , SO.MATERIAL
            , SO.ORDER_QTY_BASE 
            , SO.SALES_DOCUMENT
            , SO.SO_LOCAL_CREATE_ON_D
            , SO.DELIVERY
            , SO.DO_LOCAL_CREATE_ON_D
            , SO."1ST_GI_NO"
            , SO."1ST_GI_LOCAL_CREATE"
            , SO."2ND_GI_NO"
            , SO."2ND_GI_CREATE_ON"
            , SO.BILLING_DOC
            , SO.BILLING_CREATE_ON
            , SO.SPEC_PROCESSING
            , SO.REJECT_REASON_1
        FROM OW_LAO.TMP_D2C_MELI_COLETAS JP
        INNER JOIN OW_LAO.ODS_NERP_ZRSDD6A120_SALES_ORDER_TRACKING SO
            ON JP."SEQUENCE" = SO.CUSTOMER_PO 
           AND JP.REFERENCE_CODE = SO.MATERIAL
           AND SO.ORDER_QTY_BASE > 0
    ) SO
      ON JP."SEQUENCE" = SO.CUSTOMER_PO 
     AND JP.REFERENCE_CODE = SO.MATERIAL
    LEFT JOIN (
        SELECT JP.ORDER_ID
             , JP."SEQUENCE"
             , OT.MATERIAL
             , OT.DELIVERY_NO
             , OT.DELIVERY_ITEM
             , RT.RDO_NUMBER
             , RT.RDO_ORDER_TYPE
             , RT.GR_DATE
             , RT.RDO_RETURN_IOD_DATE
             , RT.LAST_OCCURRENCE
             , RT.RETURN_REASON_DESC
        FROM OW_LAO.ODS_NERP_ZRSDD6A120_SALES_ORDER_TRACKING SO
        INNER JOIN (SELECT DISTINCT ORDER_ID, "SEQUENCE" FROM OW_LAO.TMP_JSON_PACKAGE_ATTACHMENT) JP
            ON JP."SEQUENCE" = SO.CUSTOMER_PO 
           AND SO.ORDER_QTY_BASE > 0
        INNER JOIN OW_LAO.ODS_NERP_ZLLEJ50090_OUTBOUND_TRACKING OT
            ON OT.REFERENCE_DOC_SO_PO = SO.SALES_DOCUMENT 
           AND OT.MATERIAL = SO.MATERIAL 
           AND OT.DELIVERY_NO = SO.DELIVERY
           AND OT.DELIVERY_ITEM = SO.DELIVERY_ITEM
           AND OT.DO_TYPE = 'ZND1'
        INNER JOIN OW_SEDA_S.VW_CELLO_RETURN_TRACKING RT
            ON RT.ORIG_DO_NO = OT.DELIVERY_NO
           AND RT.MATERIAL_CODE = OT.MATERIAL
           AND RT.RDO_DELIVERY_TYPE <> 'DUMMY'
    ) CL
      ON JP.ORDER_ID = CL.ORDER_ID
     AND JP.REFERENCE_CODE = CL.MATERIAL
    LEFT JOIN (
        SELECT JP.ORDER_ID
             , JP."SEQUENCE"
             , OT.NFE_NUM_BILLTO
             , OT.MATERIAL
             , OT.DELIVERY_NO
             , OT.DELIVERY_ITEM
             , OT.EPOD_DATE
             , OT.NOTA_INTERNAL_NO
             , OT.NOTA_POSTING_DATE
        FROM OW_LAO.ODS_NERP_ZRSDD6A120_SALES_ORDER_TRACKING SO
        INNER JOIN OW_LAO.ODS_NERP_ZLLEJ50090_OUTBOUND_TRACKING OT
            ON OT.REFERENCE_DOC_SO_PO = SO.SALES_DOCUMENT 
           AND OT.MATERIAL = SO.MATERIAL 
           AND OT.DELIVERY_NO = SO.DELIVERY
           AND OT.DELIVERY_ITEM = SO.DELIVERY_ITEM
           AND OT.DO_TYPE = 'ZND1'
           AND SO.ORDER_QTY_BASE > 0
        INNER JOIN (SELECT DISTINCT ORDER_ID, "SEQUENCE", INVOICENUMBER FROM OW_LAO.TMP_JSON_PACKAGE_ATTACHMENT) JP
            ON JP."SEQUENCE" = SO.CUSTOMER_PO 
           AND JP.INVOICENUMBER = OT.NFE_NUM_BILLTO
    ) NF
      ON JP.ORDER_ID = NF.ORDER_ID
     AND JP.REFERENCE_CODE = NF.MATERIAL;

    -- Cleanup
    PERFORM TRUNCATE TABLE OW_LAO.TMP_D2C_MELI_COLETAS;
    PERFORM DROP TABLE IF EXISTS OW_LAO.TMP_JSON_PACKAGE_ATTACHMENT;
    PERFORM DROP TABLE IF EXISTS OW_LAO.TMP_PARAMETER_MELI_COLETAS;

END;
$$;

-- CALL OW_LAO.PROC_D2C_MELI_COLETAS(NULL, NULL);